### ISSUE TITLE
export 'Store' was not found in 'redux'

### ISSUE THREAD

**Issue by IAmRaszagal** [ng-book/angular2-redux-chat#4]
Like the title says, I get 8 warnings that Store was not found in redux.
This is in a freshly cloned, newly npm-installed copy of this project.
 I tried to "Google with Bing", but I couldn't find anything about this problem. 
Any tips? Cause I would really like to play around with this project to get a better understanding about redux in Angular.

Thanks in advance.

**Comment by IAmRaszagal** [comment]
Hmmm... Apparently it just took a while, cause after having made this issue, I went to Google some more.
Then when I switched back to the tab running this project it had loaded up... 
Guess it wasn't "fatal" warnings. Sorry to have bothered you >.<

**Comment by jkyoutsey** [comment]
Actually, this IS an issue.  I'm getting it with redux 3.7.1 and **AoT** compilation:
`@angular/cli: 1.2.0 // also happens with 1.1.0
node: 6.10.3
os: darwin x64
@angular/animations: 4.2.6
@angular/common: 4.2.6
@angular/compiler: 4.2.6
@angular/core: 4.2.6
@angular/forms: 4.2.6
@angular/http: 4.2.6
@angular/platform-browser: 4.2.6
@angular/platform-browser-dynamic: 4.2.6
@angular/router: 4.2.6
@angular/cli: 1.2.0
@angular/compiler-cli: 4.2.6
@angular/language-service: 4.2.6`

Based on the latest version of the book I'm using:
`import * as Redux from 'redux';`
and
`@Inject(AppStore) private store: Redux.Store<AppState>`
Which results in:
`WARNING in ./src/main/ui/app/app.component.ts
77:64-75 "export 'Store' (imported as 'Redux') was not found in 'redux'`

The issue is with AoT compilation.  Otherwise it works fine.
